# Generated by Django 3.1.3 on 2020-11-30 17:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=6)),
                ('attrs', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FollowedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=6)),
                ('attrs', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SoldListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=6)),
                ('attrs', models.JSONField(default=dict)),
                ('date_of_sale', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('current_listings', models.ManyToManyField(db_column='current_listings', related_name='current_listings', to='Listings.CurrentListing')),
                ('followings', models.ManyToManyField(db_column='followings', related_name='followings', to='Listings.FollowedListing')),
                ('purchases', models.ManyToManyField(db_column='purchases', related_name='purchases', to='Listings.SoldListing')),
                ('sold_listings', models.ManyToManyField(db_column='sold_listings', related_name='sold_listings', to='Listings.SoldListing')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
