# Generated by Django 3.1.3 on 2020-11-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldlisting',
            name='date_of_sale',
        ),
    ]
